# Generated by Django 5.0.1 on 2024-01-19 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('user', '0004_alter_baseuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WastePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_purchases_bought', to='user.user')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_purchases_sold', to='user.user')),
                ('waste_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.wasteproduct')),
            ],
        ),
    ]
