# Generated by Django 5.0.1 on 2024-01-20 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_eventchat_message'),
        ('user', '0004_alter_baseuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever_chat', to='user.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_chat', to='user.user')),
            ],
        ),
    ]
