# Generated by Django 5.0.1 on 2024-01-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
