# Generated by Django 5.0.1 on 2024-01-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_baseuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('recycler', 'Recycler')], max_length=20),
        ),
    ]
