# Generated by Django 5.0.1 on 2024-01-19 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recycledproduct',
            old_name='decription',
            new_name='description',
        ),
    ]
