# Generated by Django 5.0.1 on 2024-01-19 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_decription_recycledproduct_description'),
        ('user', '0004_alter_baseuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recycledproduct',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
