# Generated by Django 5.0.1 on 2024-01-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_recycledproduct_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasteproduct',
            name='latitude',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='wasteproduct',
            name='longitude',
            field=models.TextField(null=True),
        ),
    ]
